SIMULATION_CONTROLLER:
  IP: "127.0.0.1"
  PORT: 30000
  SIMULATION_STEP_TIME_SECONDS: 0.1
  AGENT_CONTROLLER_NAME: ""
  TASK_NAME: ""

  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
      DISTANCE_TO_GOAL_SCALE: 1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0
    OBSTACLE_IGNORE_ACTOR_NAMES: []
  
  SPHERE_AGENT_CONTROLLER:
    OBSERVATION_MODE: "mixed" # "mixed" or "physical"
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    SPHERE:
      MASS_SCALE: 1.0
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0
    MIXED_MODE:
      OBSERVATION_CAMERA_ACTOR_NAME: ""
      SET_OBSERVATION_CAMERA_POSE_EGOCENTRIC: True
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      ACTION_APPLY_FORCE_SCALE: 1.0
      ACTION_ROTATE_OBSERVATION_CAMERA_SCALE: 1.0
      OBSERVATION_CAMERA_POSITION_OFFSET_X: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Y: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Z: 1.0
      YAW_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0
    PHYSICAL_MODE:
      ACTION_APPLY_FORCE_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0

  OPENBOT_AGENT_CONTROLLER:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    OBSERVATION_MODE: "mixed"
    AGENT_READY_VELOCITY_THRESHOLD: 0.0
    # Allows behavior specialization of the InteriorSimBridge classes:
    # - "yaw-x-y" the observation vector is set to be the vehicle's yaw, x position and y position in the world frame.
    # - "dist-sin-cos" the observation vector is set to be the vehicle's distance to the goal, the cos and sin components of the relative yaw between the vehicle's front (x) axis and the vector connecting the vehicle to its goal.
    PHYSICAL_OBSERVATION_MODE: ""
    MIXED_MODE:
      OBSERVATION_CAMERA_ACTOR_NAME: ""
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      SMARTPHONE_FOV: 90.0            # Field of view of the smartphone camera in [deg]
      MOTION_BLUR_AMOUNT: 0.0        # Strength of motion blur, 0:off, should be renamed to intensity
      MOTION_BLUR_MAX: 0.0            # Max distortion caused by motion blur, in percent of the screen width, 0:off
      POST_PROC_BLEND_WEIGHT: 0.0     # Range (0.0, 1.0) where 0 indicates no effect, 1 indicates full effect.

  # This will be used in code/experiments/debug_synchronization_model/DebugProject
  DEBUG_AGENT_CONTROLLER:
    AGENT_ACTOR_NAME: "SphereActor"
    FIRST_OBSERVATION_CAMERA_ACTOR_NAME: "FirstObservationCamera"
    FIRST_OBSERVATION_CAMERA_ACTOR_HEIGHT: 512
    FIRST_OBSERVATION_CAMERA_ACTOR_WIDTH: 512
    SECOND_OBSERVATION_CAMERA_ACTOR_NAME: "SecondObservationCamera"
    SECOND_OBSERVATION_CAMERA_ACTOR_HEIGHT: 512
    SECOND_OBSERVATION_CAMERA_ACTOR_WIDTH: 512

  VISUALIZER:
    CAMERA_ACTOR_NAME: ""
    SET_CAMERA_POSE: False
    CAMERA_POSITION_X: .NAN
    CAMERA_POSITION_Y: .NAN
    CAMERA_POSITION_Z: .NAN
    CAMERA_PITCH: 0.0
    CAMERA_YAW: 0.0
    CAMERA_ROLL: 0.0
