SIMULATION_CONTROLLER:
  IP: "127.0.0.1"
  PORT: 30000
  LEVEL_PATH: "/Game/Maps"
  LEVEL_PREFIX: "Map_"
  LEVEL_ID: ""

  SIMULATION_STEP_TIME_SECONDS: 0.1
  TASK_NAME: ""
  AGENT_CONTROLLER_NAME: ""
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []

  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
      DISTANCE_TO_GOAL_SCALE: 1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0
    OBSTACLE_IGNORE_ACTOR_NAMES: []

  IMITATION_LEARNING_TASK:
    TRAJECTORY_FILE: ""
    RANDOM_SPAWN_TRAJ: True
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
      DISTANCE_TO_GOAL_SCALE: 1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    TARGET_RADIUS: 10000
    ACCEPTANCE_RADIUS: 0.1
    PATH_WEIGHT_DIST: 1.0
    PATH_WEIGHT_NUM_WAYPOINTS: 1.0
    MAX_ITER_REPLAN: 10000
    AGENT_POSITION_Z_MIN: 5.0
    AGENT_POSITION_Z_MAX: 20.0
    PATH_TRAJECTORY_PAIRS: ""

  OPENBOT_AGENT_CONTROLLER:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    ACTION_MODE: "" # "low_level_control" or "teleport"
    OBSERVATION_MODE: "mixed" # "mixed" or "physical"
    WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
    AGENT_READY_VELOCITY_THRESHOLD: 0.0
    SENSORS: ["camera", "imu", "sonar"]
    CAMERA_PARAMETERS:
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      FOV: 90.0                   # Field of view of the smartphone camera in [deg]
      MOTION_BLUR_AMOUNT: 0.0     # Strength of motion blur, 0:off, should be renamed to intensity
      MOTION_BLUR_MAX: 0.0        # Max distortion caused by motion blur, in percent of the screen width, 0:off
      POST_PROC_BLEND_WEIGHT: 0.0 # Range (0.0, 1.0) where 0 indicates no effect, 1 indicates full effect
      RENDER_PASSES: ["final_color", "segmentation", "depth_glsl"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
    SONAR_PARAMETERS:
      MAX_REFLECTION_ANGLE: 45.0
      OFFSET_POSITION:
        X: 0.0
        Y: 0.0
        Z: 0.0
      OFFSET_ORIENTATION:
        ROLL: 0.0
        PITCH: 0.0
        YAW: 0.0
      HORIZONTAL_FOV: 30.0
      VERTICAL_FOV: 10.0
      DEBUG: False
      RANGE:
        MIN: 0.01
        MAX: 2.5
      NOISE_STD: 0.0
    IMU_PARAMETERS:
      DEBUG: False
      OFFSET_POSITION:
        X: 0.0
        Y: 0.0
        Z: 0.0
      OFFSET_ORIENTATION:
        ROLL: 0.0
        PITCH: 0.0
        YAW: 0.0
      ACCELEROMETER_NOISE_STD: 
        X: 0.0
        Y: 0.0
        Z: 0.0
      GYROSCOPE_NOISE_STD: 
        X: 0.0
        Y: 0.0
        Z: 0.0
      GYROSCOPE_BIAS: 
        X: 0.0
        Y: 0.0
        Z: 0.0
    NAVMESH:
      AGENT_RADIUS: 20.0
      AGENT_HEIGHT: 20.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_SLOPE: 0.1
      AGENT_MAX_STEP_HEIGHT: 2.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 400.0
      MAX_SIMPLIFINCATION_ERROR: 1.3

  SPHERE_AGENT_CONTROLLER:
    OBSERVATION_MODE: "mixed" # "mixed" or "physical"
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    SPHERE:
      MASS_SCALE: 1.0
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0
    MIXED_MODE:
      OBSERVATION_CAMERA_ACTOR_NAME: ""
      SET_OBSERVATION_CAMERA_POSE_EGOCENTRIC: True
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      ACTION_APPLY_FORCE_SCALE: 1.0
      ACTION_ROTATE_OBSERVATION_CAMERA_SCALE: 1.0
      OBSERVATION_CAMERA_POSITION_OFFSET_X: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Y: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Z: 1.0
      YAW_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
    PHYSICAL_MODE:
      ACTION_APPLY_FORCE_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0

  CAMERA_AGENT_CONTROLLER:
    CAMERA_ACTOR_NAME: ""
    RENDER_PASSES: ["final_color"]
    CAMERA_PARAMETERS:
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
      FINAL_COLOR_AUTO_EXPOSURE_OVERRIDE_SPEED_UP: False
      FINAL_COLOR_AUTO_EXPOSURE_SPEED_UP: 0.0
      FINAL_COLOR_AUTO_EXPOSURE_OVERRIDE_SPEED_DOWN: False
      FINAL_COLOR_AUTO_EXPOSURE_SPEED_DOWN: 0.0
    NAVMESH:
      AGENT_HEIGHT: 1.0
      AGENT_RADIUS: 1.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: -1.0
      AGENT_MAX_SLOPE: 1.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 0.0
      TILE_SIZE_UU: 1
      NAV_MODIFIER_OFFSET_X: 0.0
      NAV_MODIFIER_OFFSET_Y: 0.0
      NAV_MODIFIER_OFFSET_Z: 0.0
      WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
      EXPORT_NAV_DATA_OBJ: False
      EXPORT_NAV_DATA_OBJ_DIR: ""

  VISUALIZER:
    CAMERA_ACTOR_NAME: ""
    SET_CAMERA_POSE: False
    CAMERA_POSITION_X: .NAN
    CAMERA_POSITION_Y: .NAN
    CAMERA_POSITION_Z: .NAN
    CAMERA_PITCH: 0.0
    CAMERA_YAW: 0.0
    CAMERA_ROLL: 0.0
