OPENBOT:
  OPENBOT_PAWN:
  # OpenBot mesh uasset path
    MESH: /OpenBot/V0/Meshes/OpenBot_V0_Mesh.OpenBot_V0_Mesh
    # OpenBot Animation uasset class path
    ANIMATION: /OpenBot/V0/Meshes/OpenBot_V0_Animation.OpenBot_V0_Animation_C
    # Velocity constant of the OpenBot motors
    MOTOR_VELOCITY_CONSTANT: 65.89
    # Gear ratio of the OpenBot motors
    GEAR_RATIO: 50.0
    # Absolute duty cycle (in the ACTION_SCALE range) below which a command does not produces any torque on the vehicle
    CONTROL_DEAD_ZONE: 2.5
    # Motor maximal torque
    MOTOR_TORQUE_MAX: 0.19
    # Motor winding electrical resistance
    ELECTRICAL_RESISTANCE: 0.5
    # Motor winding electrical inductance
    ELECTRICAL_INDUCTANCE: 0.5
    # OpenBot action scaling factor
    ACTION_SCALE: 255
    # Voltage of the battery powering the OpenBot
    BATTERY_VOLTAGE: 12.0
  OPENBOT_WHEEL:
    AFFECTED_BY_HANDBRAKE: True
    # Radius of the wheel in [m]
    SHAPE_RADIUS: 3.3
    # Width of the wheel in [m]
    SHAPE_WIDTH: 1.5
    #
    STEER_ANGLE: 0.0
    # How far the wheel can go above the resting position in [m]
    SUSPENSION_MAX_RAISE: 0.0
    # How far the wheel can drop below the resting position in [m]
    SUSPENSION_MAX_DROP: 0.0
    # Mass of this wheel in [kg]
    MASS: 0.033
  VEHICLE_COMPONENT:
    # DragCoefficient of the vehicle chassis.
    DRAG_COEFFICIENT: 1.0
    # Chassis width used for drag force computation in [cm]
    CHASSIS_WIDTH: 15.0
    # Chassis height used for drag force computation in [cm]
    CHASSIS_HEIGHT: 15.0
    # Max RPM for engine
    MOTOR_MAX_RPM: 20000.0
  CAMERA_COMPONENT:
    POSITION_X: 5.0
    POSITION_Y: 5.0
    POSITION_Z: 5.0
    ROLL: 0.0
    YAW: 0.0
    PITCH: 0.0
    FOV: 90.0
  IMU_COMPONENT:
    POSITION_X: 5.0
    POSITION_Y: 0.0
    POSITION_Z: 5.0
    ROLL: 0.0
    YAW: 0.0
    PITCH: 0.0
  SONAR_COMPONENT:
    POSITION_X: 10.0
    POSITION_Y: 0.0
    POSITION_Z: -1.5
    ROLL: 0.0
    YAW: 0.0
    PITCH: 0.0