#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

WHEELED_VEHICLE:
  VEHICLE_PAWN:
    SKELETAL_MESH: "/WheeledVehicle/OpenBot_V1/Meshes/OpenBot_V1_Mesh.OpenBot_V1_Mesh"
    ANIM_INSTANCE: "/WheeledVehicle/OpenBot_V1/Meshes/OpenBot_V1_Animation.OpenBot_V1_Animation_C"

    CAMERA_COMPONENT:
      POSITION_X: -60.0              # Camera relative position in [cm]
      POSITION_Y: 50.0              # Camera relative position in [cm]
      POSITION_Z: 50.0             # Camera relative position in [cm]
      PITCH: -30.0                   # Camera relative orientation in [°]
      YAW: -30.0                     # Camera relative orientation in [°]
      ROLL: 0.0                    # Camera relative orientation in [°]
      FOV: 70.0                    # Camera field of view in [°]
    
    IMU_COMPONENT:
      POSITION_X: 8.0              # IMU relative position in [cm]
      POSITION_Y: 0.0              # IMU relative position in [cm]
      POSITION_Z: 10.0             # IMU relative position in [cm]
      PITCH: 0.0                   # IMU relative orientation in [°]
      YAW: 0.0                     # IMU relative orientation in [°]
      ROLL: 0.0                    # IMU relative orientation in [°]
      
    SONAR_COMPONENT:
      POSITION_X: 15.0             # Sonar relative position in [cm]
      POSITION_Y: 0.0              # Sonar relative position in [cm]
      POSITION_Z: -1.5             # Sonar relative position in [cm]
      PITCH: 0.0                   # Sonar relative orientation in [°]
      YAW: 0.0                     # Sonar relative orientation in [°]
      ROLL: 0.0                    # Sonar relative orientation in [°]

  VEHICLE_COMPONENT:
    MASS: 1.12                   # Mass of the vehicle chassis in [kg]
    DRAG_COEFFICIENT: 1.0        # DragCoefficient of the vehicle chassis
    CHASSIS_WIDTH: 15.0          # Chassis width used for drag force computation in [cm]
    CHASSIS_HEIGHT: 15.0         # Chassis height used for drag force computation in [cm]

  VEHICLE_WHEEL:
    AFFECTED_BY_HANDBRAKE: True       # Whether handbrake should affect this wheel
    MAX_BRAKE_TORQUE: 1500.0          # Max brake torque for this wheel (Nm)
    MAX_HAND_BRAKE_TORQUE: 3000.0     # Max handbrake brake torque for this wheel (Nm). A handbrake should have a stronger brake torque than the brake.
    
    LAT_STIFF_MAX_LOAD: 2.0           # Max normalized tire load at which the tire can deliver no more lateral stiffness no matter how much extra load
                                      # is applied to the tire.
    LAT_STIFF_VALUE: 17.0             # How much lateral stiffness to have given lateral slip
    LONG_STIFF_VALUE: 1000.0          # How much longitudinal stiffness to have given longitudinal slip
    
    SUSPENSION_MAX_RAISE: 0.0         # How far the wheel can go above the resting position in [m]
    SUSPENSION_MAX_DROP: 0.0          # How far the wheel can drop below the resting position in [m]
    SUSPENSION_FORCE_OFFSET: 0.0      # Vertical offset from where suspension forces are applied (along Z-axis) 
    SUSPENSION_NATURAL_FREQUENCY: 7   # Oscillation frequency of suspension. Standard cars have values between 5 and 10
    SUSPENSION_DAMPING_RATIO: 1.0     # The rate at which energy is dissipated from the spring. Standard cars have values between 0.8 and 1.2. Values < 1
                                      # are more sluggish, values > 1 or more twitchy.
    WHEEL_MASS: 0.033                 # Mass of this wheel in [kg]
    WHEEL_RADIUS: 3.3                 # Radius of the wheel in [cm]
    WHEEL_WIDTH: 2.5                  # Width of the wheel in [cm]
