#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SP_ENGINE:

  INTERACTION_MODE: "programmatic" # "interactive", "programmatic"

  IP: "127.0.0.1"
  PORT: 30000

  # Setting SCENE_ID and MAP_ID will load the following map: /Game/Scenes/SCENE_ID/Maps/MAP_ID.MAP_ID
  # If SCENE_ID is not set, the default map will be loaded. If MAP_ID is not set, it will be set to SCENE_ID.
  SCENE_ID: ""
  MAP_ID: ""

  TASK: ""
  AGENT: ""
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []

  #
  # Agents
  #

  CAMERA_AGENT:
    CAMERA_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["set_location", "set_rotation"] # "set_location", "set_rotation"
    OBSERVATION_COMPONENTS: ["camera"] # "camera"
    STEP_INFO_COMPONENTS: []
    SPAWN_MODE: "specify_pose" # "specify_existing_actor", "specify_pose"
    SPAWN_ACTOR_NAME: ""
    SPAWN_LOCATION_X: 0.0
    SPAWN_LOCATION_Y: 0.0
    SPAWN_LOCATION_Z: 0.0
    SPAWN_ROTATION_PITCH: 0.0
    SPAWN_ROTATION_YAW: 0.0
    SPAWN_ROTATION_ROLL: 0.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "depth", "final_color", "normals", segmentation"
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0

  SPHERE_AGENT:
    SPHERE_ACTOR_NAME: ""
    CAMERA_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["add_force", "add_to_rotation"] # "add_force", "add_to_rotation"
    OBSERVATION_COMPONENTS: ["camera", "location", "rotation"] #  "camera", "location", "rotation"
    STEP_INFO_COMPONENTS: ["debug"] # "debug"
    SPAWN_MODE: "specify_pose" # "specify_existing_actor", "specify_pose"
    SPAWN_ACTOR_NAME: ""
    SPAWN_LOCATION_X: 0.0
    SPAWN_LOCATION_Y: 0.0
    SPAWN_LOCATION_Z: 0.0
    SPAWN_ROTATION_PITCH: 0.0
    SPAWN_ROTATION_YAW: 0.0
    SPAWN_ROTATION_ROLL: 0.0
    SPHERE:
      STATIC_MESH: "/Engine/BasicShapes/Sphere.Sphere"
      MATERIAL: "/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"
      MESH_SCALE_X: 0.5
      MESH_SCALE_Y: 0.5
      MESH_SCALE_Z: 0.5
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "depth", "final_color", "normal", "segmentation" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0

  URDF_ROBOT_AGENT:
    URDF_ROBOT_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["control_joints"]
    OBSERVATION_COMPONENTS: ["link_state", "camera"]
    STEP_INFO_COMPONENTS: []
    SPAWN_MODE: "specify_pose" # "specify_existing_actor", "specify_pose"
    SPAWN_ACTOR_NAME: ""
    SPAWN_LOCATION_X: 0.0
    SPAWN_LOCATION_Y: 0.0
    SPAWN_LOCATION_Z: 0.0
    SPAWN_ROTATION_PITCH: 0.0
    SPAWN_ROTATION_YAW: 0.0  
    SPAWN_ROTATION_ROLL: 0.0
    IS_READY_VELOCITY_THRESHOLD: 1.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "depth", "final_color", "normal", "segmentation" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0

  VEHICLE_AGENT:
    VEHICLE_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["set_brake_torques", "set_drive_torques"] # "set_brake_torques", "set_drive_torques"
    OBSERVATION_COMPONENTS: ["camera", "location", "rotation", "wheel_rotation_speeds"] # "camera", "imu", "location", "rotation", "wheel_rotation_speeds"
    STEP_INFO_COMPONENTS: [""]
    SPAWN_MODE: "specify_pose" # "specify_existing_actor", "specify_pose"
    SPAWN_ACTOR_NAME: ""
    SPAWN_LOCATION_X: 0.0
    SPAWN_LOCATION_Y: 0.0
    SPAWN_LOCATION_Z: 0.0
    SPAWN_ROTATION_PITCH: 0.0
    SPAWN_ROTATION_YAW: 0.0
    SPAWN_ROTATION_ROLL: 0.0
    IS_READY_VELOCITY_THRESHOLD: 0.001
    CAMERA:
      RENDER_PASSES: ["final_color"] # "depth", "final_color", "normal", "segmentation" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0

  #
  # Sensors
  #

  CAMERA_SENSOR:
    USE_SHARED_MEMORY: True # write image data to shared memory for fast interprocess communication
    READ_SURFACE_DATA: True # read image data from the GPU, useful for debugging and benchmarking

  IMU_SENSOR:
    DEBUG_RENDER: False

  #
  # Tasks
  #

  IMITATION_LEARNING_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    EPISODES_FILE: ""
    AGENT_SPAWN_OFFSET_LOCATION_X: 0.0
    AGENT_SPAWN_OFFSET_LOCATION_Y: 0.0
    AGENT_SPAWN_OFFSET_LOCATION_Z: 0.0

  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    GOAL_MESH: "/Engine/BasicShapes/Cylinder.Cylinder"
    GOAL_MATERIAL: "/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
    EPISODE_BEGIN:
      AGENT_LOCATION_X_MIN: .NAN
      AGENT_LOCATION_X_MAX: .NAN
      AGENT_LOCATION_Y_MIN: .NAN
      AGENT_LOCATION_Y_MAX: .NAN
      AGENT_LOCATION_Z: .NAN
      GOAL_LOCATION_X_MIN: .NAN
      GOAL_LOCATION_X_MAX: .NAN
      GOAL_LOCATION_Y_MIN: .NAN
      GOAL_LOCATION_Y_MAX: .NAN
      GOAL_LOCATION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0

  #
  # Other top-level SimulationController classes
  #

  NAVMESH:
    TILE_POOL_SIZE: 1024
    TILE_SIZE_UU: 1000.0
    CELL_SIZE: 1.0
    CELL_HEIGHT: 1.0
    AGENT_RADIUS: 50.0
    AGENT_HEIGHT: 200.0
    AGENT_MAX_SLOPE: 1.0
    AGENT_MAX_STEP_HEIGHT: 1.0
    MIN_REGION_AREA: 100.0
    MERGE_REGION_SIZE: 400.0
    MAX_SIMPLIFICATION_ERROR: 1.3
    DEBUG_NAVIGATION_DATA_FILE: ""

  #
  # Unreal systems
  #

  PHYSICS:
    SIMULATION_STEP_TIME: 0.05
    ENABLE_ENHANCED_DETERMINISM: True
    ENABLE_SUBSTEPPING: True
    MAX_SUBSTEP_DELTA_TIME: 0.01
    MAX_SUBSTEPS: 100
